version: "3"
services:

 ticket_db:
  image: postgres:latest
  restart: unless-stopped
  container_name: ticket_db
  volumes:
    - ./postgres-data:/var/lib/postgresql/data
  env_file:
   - .env

 ticket_redis:
  image: redis
  restart: unless-stopped
  container_name: ticket_redis

 ticket_api:
  build: ./code
  container_name: ticket_api
  restart: unless-stopped
  ports:
   - "${DJANGO_PORT}:8080"
  env_file:
   - .env
  volumes:
   - ./code:/code
  depends_on:
   - ticket_db
   - ticket_redis
  links:
   - ticket_db:ticket_db
   - ticket_redis:ticket_redis
  command: "runserver 0.0.0.0:8080"

 ticket_celery:
  build: ./code
  restart: unless-stopped
  container_name: ticket_celery
  entrypoint: celery -A config worker -l info
  env_file:
    - .env
  volumes:
    - ./code:/code
  depends_on:
    - ticket_db
    - ticket_redis
